config/routes.rb
Rails.application.routes.draw do
  resources :pages

  root to: "pages#index"

end

app/models/page.rb
require 'redcarpet'

class Page < ActiveRecord::Base
    extend FriendlyId
    friendly_id :title, use: :slugged

    def should_generate_new_friendly_id?
        new_record?
    end

    def redcarpet_render
        markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, fenced_code_blocks: true, filter_html: true, hard_wrap: true, no_intraemphasis: true, gh_blockcode: true, strikethrough: true, highlight: true, )
        return SyntaxHighlighter.new(markdown.render(self.body)).hightlight_html.html_safe
    end

end


class SyntaxHighlighter
  require 'net/http'
  require 'uri'
  require 'nokogiri'

  PYGMENTS_URI = 'http://pygments.simplabs.com/'

  def initialize(html)
    @html = html
  end

  def hightlight_html
    doc = Nokogiri::HTML(@html)
    doc.search('pre > code[class]').each do |code|
      request = Net::HTTP.post_form(URI.parse(PYGMENTS_URI),
                  {'lang' => code[:class],
                   'code' => code.text.rstrip})

      code.parent.replace request.body
    end
    out = Nokogiri::HTML.fragment(doc.to_s)
    out.to_html
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    # GET /pages/new
    def new
        @page = Page.new
        if params.has_key?(:id)
            @page.title =  params[:id]
        end
    end

    # GET /page
    def index
        @pages = Page.all
    end

    def show
        if Page.friendly.where(:slug => params[:id].downcase).blank?
            redirect_to  :action => 'new', :id => params[:id]
        else
            @page = Page.friendly.find(params[:id].downcase)
        end
    end

    # POST /page
    def create
        @page = Page.new(page_params)
        @page.save
        redirect_to @page, notice: 'Page was successfully created.'
    end

    #PATCH/PUT /page/1
    #PATCH/PUT /page/1.json
    respond_to :html, :json
    def update
        @page = Page.friendly.find params[:id]

        respond_to do |format|
            if @page.update_attributes(page_params)
                format.html { redirect_to(@page, :notice => 'Page was successfully updated.') }
                format.json { respond_with_bip(@page) }
            else
                format.html { redirect_to @page, notice: 'There was a error trying to update the page.' }
                format.json { respond_with_bip(@page) }
            end
        end
    end

      # DELETE /links/1
      # DELETE /links/1.json
      def destroy
       @page = Page.friendly.find(params[:id])
       @page.destroy
        respond_to do |format|
          format.html { redirect_to pages_path, notice: 'Page was successfully destroyed.' }
          format.json { head :no_content }
       end


end

private
  # Use callbacks to share common setup or constraints between actions.
  def set_pages
      @page = Page.friendly.find(params[:id])
  end

    # Never trust parameters from the scary internet, only allow the white list through.
    def page_params
      params.require(:page).permit(:title, :body)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wiki</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link data-turbolinks-track="true" href="/assets/code.css" media="all" rel="stylesheet" />
  <link data-turbolinks-track="true" href="/assets/md.css" media="all" rel="stylesheet" />
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>
<div id="header">
  <center><h1><a href="/">MDTN Wiki</a></h1></center>
</div>
    <% flash.each do |name, msg| -%>
          <%= content_tag :div, msg, class: name %>
    <% end -%>
<%= yield %>

</body>
</html>

app/views/pages/_form.html.erb
<%= form_for(@page) do |form| %>

  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </fieldset>
  <fieldset>
    <%= form.label :body %>
    <%= form.text_area :body %>
  </fieldset>
  <fieldset>
    <%= form.submit %>
  </fieldset>
<% end %>

app/views/pages/index.html.erb
<div id="main">
   <% for page in Page.all %>
    <section class="controls">
      <%= link_to page.title, page_path(page), class: "page" %>
      <%= link_to '[delete]', page, method: :delete, data: { confirm: 'Are you sure?' } , class: "remove" %>
    </section>
  <% end %>
</div>
<div id="sidebar">
  <p><%= link_to "Create a new page", new_page_path %></p>
  <center><h3>Existing pages</h3></center>
  <% for page in Page.all %>
    <%= link_to page.title, page_path(page)%>
    <br>
  <% end %>

app/views/pages/new.html.erb
<div id="main">
    <%= link_to 'Back', pages_path %>
    <%=render 'form' %>
    <%= link_to 'Back', pages_path %>
</div>

app/views/pages/show.html.erb
<div id="main">
	<h1><%= best_in_place @page, :title, :type => :input %></h1>
            <%= best_in_place @page, :body, :type => :textarea, :display_as => "redcarpet_render",  :ok_button => "Save", :activator => ".edit" %>
            <section class="page-controls">
            <a href="#" class="edit" >Edit..</a>&nbsp;|&nbsp;
            <%= link_to 'Remove...', @page, method: :delete, data: { confirm: 'Are you sure?' } , class: "remove" %>
            </section>
</div>
<div id="sidebar">
  <p><%= link_to "Create a page", new_page_path %></p>
  <center><h3>Existing pages</h3></center>
  <% for page in Page.all %>
    <%= link_to page.title, page_path(page)%>
    <br>
  <% end %>